@tab demo0
split: v {
  split: h {
    pane "worker": python3 tracker_worker.py
    pane "gateway": python3 gateway_udp_zmq.py
  }
  split: h {
    pane "bash": bash
    pane "client": python3 ground_client.py
  }
}
